[project]
name = ""
version = ""
description = ""
authors = [
    {name = "J-Stuff", email = "jstuff@j-stuff.net"},
]
dependencies = [
    "Red-DiscordBot>=3.5.4",
]
requires-python = "==3.8.10"
readme = "README.md"
license = {text = "GPL-3.0"}

